# GENERATED BY CHATGPT

# Choose Your Own Adventure Game
# Structure:
# Start -> 2 paths
# Each path -> 3 branches
# Each branch -> 2 endings


import os
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

client = OpenAI(
    api_key=os.getenv("GPT_API_KEY")
)



def ai_continue(story_context):
    response = client.chat.completions.create(
        model="gpt-5.5",
        messages=[
            {
                "role": "system",
                "content": (
                    "You are continuing a fantasy choose-your-own-adventure game. "
                    "Write a short continuation and give exactly 3 choices."
                )
            },
            {
                "role": "user",
                "content": story_context
            }
        ],
        temperature=0.9
    )

    return response.choices[0].message.content


print("Welcome to the Adventure!")

print("\nChoose a path:")
print("1. Forest")
print("2. Castle")

choice = input("> ")

# ---------------- FOREST ----------------
if choice == "1":
    print("\nYou enter the forest.")
    print("1. Follow the river")
    print("2. Enter the cave")

    forest_choice = input("> ")

    if forest_choice == "1":
        print("\nYou discover glowing water.")
        print("1. Drink it")
        print("2. Ignore it")

        river_choice = input("> ")

        if river_choice == "1":
            print("\nThe magic transforms you into a forest guardian.")
            print("\n--- AI CONTINUES THE STORY ---\n")

            ai_story = ai_continue(
                "The player became a forest guardian after drinking magical water."
            )

            print(ai_story)

        elif river_choice == "2":
            print("\nYou safely continue your journey.")

        else:
            print("Invalid choice.")

    elif forest_choice == "2":
        print("\nA dragon sleeps inside the cave.")

    else:
        print("Invalid choice.")

# ---------------- CASTLE ----------------
elif choice == "2":
    print("\nYou approach the ancient castle.")

else:
    print("Invalid choice.")