# GENERATED BY CHATGPT

# Choose Your Own Adventure Game
# Structure:
# Start -> 2 paths
# Each path -> 3 branches
# Each branch -> 2 endings
# AI continues infinitely after certain endings

import os
from dotenv import load_dotenv
from openai import OpenAI

# Load environment variables from .env
load_dotenv()

# Create OpenAI client
client = OpenAI(
    api_key=os.getenv("GPT_API_KEY")
)


# ---------------- AI FUNCTION ----------------
def ai_continue(story_context):
    response = client.chat.completions.create(
        model="gpt-4.1",
        messages=[
            {
                "role": "system",
                "content": (
                    "You are continuing a fantasy choose-your-own-adventure game.\n"
                    "Keep the story exciting and immersive.\n"
                    "Always give EXACTLY 3 choices at the end.\n"
                    "Keep responses under 200 words.\n"
                    "Format choices exactly like this:\n"
                    "1. Choice one\n"
                    "2. Choice two\n"
                    "3. Choice three"
                )
            },
            {
                "role": "user",
                "content": story_context
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content


# ---------------- AI GAME LOOP ----------------
def start_ai_loop(starting_context):

    story_context = starting_context

    while True:

        print("\n--- AI CONTINUES THE STORY ---\n")

        # Generate AI story
        ai_story = ai_continue(story_context)

        print(ai_story)

        # Save AI response into memory
        story_context += f"\nNarrator: {ai_story}"

        # Get player response
        player_action = input(
            "\nWhat do you do? (type 'quit' to end)\n> "
        )

        # Quit option
        if player_action.lower() == "quit":
            print("\nThanks for playing!")
            break

        # Save player response into memory
        story_context += f"\nPlayer: {player_action}"


# ---------------- START OF GAME ----------------

print("Welcome to the Adventure!")

print("\nChoose a path:")
print("1. Forest")
print("2. Castle")

choice = input("> ")


# ---------------- FOREST ----------------
if choice == "1":

    print("\nYou enter the forest.")
    print("1. Follow the river")
    print("2. Enter the cave")

    forest_choice = input("> ")

    # ---------------- RIVER ----------------
    if forest_choice == "1":

        print("\nYou discover glowing water.")
        print("1. Drink it")
        print("2. Ignore it")

        river_choice = input("> ")

        # AI branch
        if river_choice == "1":

            print(
                "\nThe magic transforms you into a forest guardian."
            )

            start_ai_loop(
                "The player became a forest guardian after drinking magical water."
            )

        # Normal ending
        elif river_choice == "2":

            print(
                "\nYou safely continue your journey."
            )

        else:
            print("Invalid choice.")

    # ---------------- CAVE ----------------
    elif forest_choice == "2":

        print("\nA dragon sleeps inside the cave.")
        print("1. Sneak past the dragon")
        print("2. Wake the dragon")

        cave_choice = input("> ")

        # AI branch
        if cave_choice == "1":

            print(
                "\nYou quietly sneak deeper into the cave and discover ancient ruins."
            )

            start_ai_loop(
                "The player discovered ancient ruins beneath a dragon's cave."
            )

        # Normal ending
        elif cave_choice == "2":

            print(
                "\nThe dragon awakens and stares directly into your soul."
            )

        else:
            print("Invalid choice.")

    else:
        print("Invalid choice.")


# ---------------- CASTLE ----------------
elif choice == "2":

    print("\nYou approach the ancient castle.")
    print("1. Enter the throne room")
    print("2. Climb the tower")

    castle_choice = input("> ")

    # ---------------- THRONE ROOM ----------------
    if castle_choice == "1":

        print("\nA ghostly king sits upon the throne.")
        print("1. Speak to the king")
        print("2. Run away")

        throne_choice = input("> ")

        # AI branch
        if throne_choice == "1":

            print(
                "\nThe ghostly king offers you a dangerous quest."
            )

            start_ai_loop(
                "The player accepted a dangerous quest from a ghostly king."
            )

        # Normal ending
        elif throne_choice == "2":

            print(
                "\nYou escape the castle safely."
            )

        else:
            print("Invalid choice.")

    # ---------------- TOWER ----------------
    elif castle_choice == "2":

        print("\nAt the top of the tower, you find a magical telescope.")
        print("1. Look through it")
        print("2. Destroy it")

        tower_choice = input("> ")

        # AI branch
        if tower_choice == "1":

            print(
                "\nThe telescope reveals another world beyond the stars."
            )

            start_ai_loop(
                "The player discovered another world through a magical telescope."
            )

        # Normal ending
        elif tower_choice == "2":

            print(
                "\nThe tower begins collapsing around you!"
            )

        else:
            print("Invalid choice.")

    else:
        print("Invalid choice.")


# ---------------- INVALID START ----------------
else:
    print("Invalid choice.")